name: dev env
on:
  pull_request:
    paths:
      - '.pre-commit-config.yaml'
      - 'Makefile'
      - '.github/workflows/development-environment.yml'
      - 'requirements-*.txt'
      - '.python-version'
      - '.envrc'
      - 'Brewfile'
      - 'scripts/*'
      - 'tools/*'
      - 'src/sentry/runner/commands/devserver.py'
      - 'src/sentry/runner/commands/devservices.py'
      - 'bin/load-mocks'

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# hack for https://github.com/actions/cache/issues/810#issuecomment-1222550359
env:
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 3

jobs:
  pyenv-setup:
    name: pyenv set up
    runs-on: macos-11
    timeout-minutes: 25
    env:
      # This is to support this code https://github.com/getsentry/sentry/blob/47b837a69c38e190a7555de81e6d7d216498b854/scripts/pyenv_setup.sh#L17-L40
      SHELL: /bin/zsh

    steps:
      - name: Checkout sentry
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Install pyenv
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install pyenv

      # Only after we source ~/.zprofile that the right Python will be selected
      - name: Set up pyenv
        run: |
          make setup-pyenv
          [[ $(which python) != "${HOME}/.pyenv/shims/python" ]]
          source ~/.zprofile
          [[ $(which python) == "${HOME}/.pyenv/shims/python" ]]
          [[ $(python -V) == "Python $(cat .python-version)" ]]
          python -m venv .venv
          source .venv/bin/activate
          [[ $(python -V) == "Python $(cat .python-version)" ]]

  tools-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - uses: getsentry/action-setup-venv@9e3bbae3836b1b6f129955bf55a19e1d99a61c67 # v1.0.5
        with:
          python-version: 3.8.16
          cache-dependency-path: |
            requirements-dev.txt
            requirements-dev-frozen.txt
          install-cmd: pip install -r requirements-dev.txt -c requirements-dev-frozen.txt
      - name: run tests
        run: make test-tools
      - name: Handle artifacts
        uses: ./.github/actions/artifacts
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  # We don't yet test the bootstrap step
  # https://github.com/getsentry/bootstrap-sentry/blob/7af557be84920dd587e48613dbc308c937bc0e08/bootstrap.sh#L618-L619
  bootstrap-script:
    runs-on: macos-11
    timeout-minutes: 40
    env:
      # Make the environment more similar to what Mac defaults to
      SHELL: /bin/zsh

    steps:
      - name: Run bootstrap code
        env:
          STRAP_DEBUG: 1
          # This ensures that the bootstrap code will test against this branch
          CI_CHECKOUT_BRANCH: ${{ github.head_ref || github.sha }}
        run: |
          bash <(curl -s https://raw.githubusercontent.com/getsentry/bootstrap-sentry/main/bootstrap.sh)
